### ISSUE TITLE
Tracking issue for overall progress

### ISSUE THREAD

**Issue by mersinvald** [andrew-it/HotelManagementSystem#41]
### Main tasks:
- [ ] All API methods are covered with integration tests (10)
- [ ] Reports of all testing levels (unit, API, UI) (10)
- [ ] All positive tests are passed (8)
- [ ] API spec (8)
- [ ] Static analysis report with no Critical or Blocker (8)
- [ ] Load testing report (6)

### Additional tasks:
- [ ] 2+ negative tests for every positive API test (+5)
- [ ] API in swagger-ui (+3)
- [ ] Logging tests (+3)
- [ ] Non-functional testing (+2)

### More details:
Unit testing:
- [ ]  Test report
- [ ] Close to 100% coverage (we have 85%)
- [ ] Mutation testing (optional)

Integration testing:
- [ ] All methods should be covered by positive tests (minimum)
- [ ] Negative tests to break logic
- [ ] Negative tests to crash the app
- [ ] Boundary testing (by equivalent classes)
- [ ] Test report

### Presentation:
- [ ] Project state before and after
- [ ] Chosen methods and instruments
- [ ] Review and conclusion

### Final Report:
- [ ] PDF with following info about every test level (unit, integration, UI)
- [ ] Test count
- [ ] Failed tests count
- [ ] Approximate coverage
- [ ] Count and relation of positive tests to negative
- [ ] For unit and integration test levels: coverage
- [ ] For load testing: test scheme, load and response time graphs
- [ ] Attach test reports for each test level
